import React from 'react';
import { motion } from 'motion/react';
import { Sparkles, Bot, Shield, Zap, BookOpen, Brain, Code, BarChart3 } from 'lucide-react';

interface LandingPageProps {
  onGetStarted: () => void;
  onSignIn: () => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onGetStarted, onSignIn }) => {
  const features = [
    {
      icon: Bot,
      title: 'AI-Powered Learning',
      description: 'Personalized roadmaps generated by advanced AI to match your goals and experience level.',
      color: 'from-purple-500 to-blue-500',
    },
    {
      icon: Brain,
      title: 'Interactive Mentor',
      description: 'Chat with an AI mentor for explanations, quizzes, and study plans tailored to your progress.',
      color: 'from-blue-500 to-cyan-500',
    },
    {
      icon: Code,
      title: 'Hands-on Projects',
      description: 'Build real projects with guided exercises and coding challenges to reinforce learning.',
      color: 'from-amber-500 to-orange-500',
    },
    {
      icon: BarChart3,
      title: 'Progress Analytics',
      description: 'Track your XP, streaks, and learning velocity with detailed analytics and insights.',
      color: 'from-emerald-500 to-teal-500',
    },
    {
      icon: Shield,
      title: 'Secure & Private',
      description: 'Your learning data is encrypted and stored securely, accessible only to you.',
      color: 'from-indigo-500 to-violet-500',
    },
    {
      icon: Zap,
      title: 'PWA Support',
      description: 'Install the app and learn offline with full Progressive Web App capabilities.',
      color: 'from-pink-500 to-rose-500',
    },
  ];

  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white">
      <div className="max-w-4xl mx-auto px-4 py-12">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <div className="w-20 h-20 mx-auto mb-6 rounded-2xl bg-gradient-to-tr from-purple-500 to-blue-600 flex items-center justify-center shadow-lg">
            <Sparkles className="w-10 h-10 text-white" />
          </div>
          <h1 className="font-display font-extrabold text-4xl md:text-5xl text-white mb-4">
            LearnPath <span className="text-purple-400">AI</span>
          </h1>
          <p className="text-lg text-zinc-400 max-w-2xl mx-auto">
            Premium Full-Stack AI Learning Platform. Generate custom roadmaps, track progress, and master skills with AI guidance.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center mt-8">
            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={onGetStarted}
              className="px-8 py-3 font-bold text-sm text-white bg-gradient-to-br from-purple-500 to-blue-600 rounded-xl hover:brightness-110 transition-all shadow-lg"
            >
              Get Started - It's Free
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={onSignIn}
              className="px-8 py-3 font-bold text-sm text-white bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition-all"
            >
              Sign In
            </motion.button>
          </div>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-16">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 + index * 0.1, duration: 0.5 }}
              className="p-6 rounded-2xl bg-[#111111] border border-white/5 hover:border-white/10 transition-all"
            >
              <div className={`w-12 h-12 rounded-xl bg-gradient-to-tr ${feature.color} flex items-center justify-center mb-4`}>
                <feature.icon className="w-6 h-6 text-white" />
              </div>
              <h3 className="font-bold text-lg text-white mb-2">{feature.title}</h3>
              <p className="text-xs text-zinc-400">{feature.description}</p>
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8, duration: 0.6 }}
          className="text-center p-8 rounded-2xl bg-gradient-to-br from-purple-500/10 to-blue-500/10 border border-purple-500/20"
        >
          <BookOpen className="w-12 h-12 text-purple-400 mx-auto mb-4" />
          <h2 className="font-display font-bold text-2xl text-white mb-2">
            Ready to accelerate your learning?
          </h2>
          <p className="text-sm text-zinc-400 mb-6">
            Join thousands of learners building skills with AI-powered personalized curriculums.
          </p>
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={onGetStarted}
            className="px-8 py-3 font-bold text-sm text-white bg-gradient-to-br from-purple-500 to-blue-600 rounded-xl hover:brightness-110 transition-all shadow-lg"
          >
            Create Your First Roadmap
          </motion.button>
        </motion.div>
      </div>
    </div>
  );
};

export default LandingPage;