import React from 'react';
import { ArrowLeft, Shield, FileText } from 'lucide-react';

interface LegalPageProps {
  onBack: () => void;
}

// ---------------------------------------------------------------------------
// Shared layout wrapper
// ---------------------------------------------------------------------------
function LegalLayout({ title, icon: Icon, onBack, children }: { title: string; icon: React.ElementType; onBack: () => void; children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white">
      <div className="max-w-3xl mx-auto px-4 py-10">
        <button
          onClick={onBack}
          className="flex items-center gap-2 text-sm text-zinc-400 hover:text-white mb-8 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
        <div className="flex items-center gap-3 mb-8">
          <div className="w-10 h-10 rounded-xl bg-purple-500/20 flex items-center justify-center">
            <Icon className="w-5 h-5 text-purple-400" />
          </div>
          <h1 className="text-2xl font-bold text-white">{title}</h1>
        </div>
        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-zinc-300 leading-relaxed">
          {children}
        </div>
        <p className="mt-10 text-xs text-zinc-600 border-t border-white/5 pt-6">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-base font-semibold text-white mb-2">{title}</h2>
      <div className="text-sm text-zinc-400 space-y-2">{children}</div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Terms of Service
// ---------------------------------------------------------------------------
export function TermsPage({ onBack }: LegalPageProps) {
  return (
    <LegalLayout title="Terms of Service" icon={FileText} onBack={onBack}>
      <Section title="1. Acceptance of Terms">
        <p>
          By creating an account or using LearnPath AI ("the Service"), you agree to be bound by
          these Terms of Service. If you do not agree, do not use the Service.
        </p>
      </Section>

      <Section title="2. Description of Service">
        <p>
          LearnPath AI is an AI-powered learning platform that generates personalised learning
          roadmaps, lesson content, quizzes, and mentor interactions. The Service is provided
          "as-is" and may change at any time without notice.
        </p>
      </Section>

      <Section title="3. Account Responsibilities">
        <p>You are responsible for:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Maintaining the confidentiality of your account credentials.</li>
          <li>All activity that occurs under your account.</li>
          <li>Providing accurate registration information.</li>
          <li>Notifying us immediately of any unauthorised use of your account.</li>
        </ul>
      </Section>

      <Section title="4. Acceptable Use">
        <p>You agree not to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Use the Service for any unlawful purpose.</li>
          <li>Attempt to reverse-engineer, scrape, or extract model outputs at scale.</li>
          <li>Circumvent rate limits or security controls.</li>
          <li>Submit content that is harmful, abusive, or violates third-party rights.</li>
          <li>Share your account credentials with others.</li>
        </ul>
      </Section>

      <Section title="5. AI-Generated Content">
        <p>
          Roadmaps, lessons, and other content are generated by large language models. We do not
          guarantee accuracy or completeness. Always verify critical information from authoritative
          sources before applying it in professional or academic contexts.
        </p>
      </Section>

      <Section title="6. Intellectual Property">
        <p>
          The LearnPath AI platform, including its design, code, and branding, is owned by us. AI-
          generated content produced for your account belongs to you, subject to the licences of
          the underlying model providers. You grant us a non-exclusive licence to store and deliver
          that content to you.
        </p>
      </Section>

      <Section title="7. Termination">
        <p>
          We reserve the right to suspend or terminate accounts that violate these Terms. You may
          delete your account at any time; upon deletion, your personal data will be removed within
          30 days subject to legal retention obligations.
        </p>
      </Section>

      <Section title="8. Disclaimer of Warranties">
        <p>
          The Service is provided without warranty of any kind, express or implied, including
          merchantability, fitness for a particular purpose, or non-infringement. We do not warrant
          that the Service will be uninterrupted or error-free.
        </p>
      </Section>

      <Section title="9. Limitation of Liability">
        <p>
          To the fullest extent permitted by law, LearnPath AI shall not be liable for any
          indirect, incidental, or consequential damages arising from your use of the Service.
        </p>
      </Section>

      <Section title="10. Changes to Terms">
        <p>
          We may update these Terms at any time. Continued use after changes constitutes acceptance.
          We will notify registered users of material changes by email where possible.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          Questions about these Terms? Reach us at{' '}
          <a href="mailto:legal@learnpath.ai" className="text-purple-400 hover:underline">
            legal@learnpath.ai
          </a>
          .
        </p>
      </Section>
    </LegalLayout>
  );
}

// ---------------------------------------------------------------------------
// Privacy Policy
// ---------------------------------------------------------------------------
export function PrivacyPage({ onBack }: LegalPageProps) {
  return (
    <LegalLayout title="Privacy Policy" icon={Shield} onBack={onBack}>
      <Section title="1. What We Collect">
        <p>We collect the following information to provide the Service:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong className="text-white">Account data:</strong> email address, hashed password, display name.</li>
          <li><strong className="text-white">Learning data:</strong> roadmaps, lesson progress, XP, streaks, quiz scores.</li>
          <li><strong className="text-white">Usage data:</strong> structured server logs (IP address, request path, response time) retained for 30 days.</li>
          <li><strong className="text-white">Error data:</strong> crash reports via Sentry, including stack traces and browser metadata (no personal content).</li>
        </ul>
      </Section>

      <Section title="2. How We Use Your Data">
        <p>Your data is used exclusively to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Authenticate you and maintain your session.</li>
          <li>Store and serve your personalised learning content.</li>
          <li>Generate AI recommendations tailored to your progress.</li>
          <li>Debug errors and improve the platform.</li>
        </ul>
        <p>We do not sell or share your personal data with third parties for marketing.</p>
      </Section>

      <Section title="3. Third-Party Services">
        <p>We use the following third-party processors:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong className="text-white">Neon (PostgreSQL):</strong> stores all user and learning data.</li>
          <li><strong className="text-white">OpenRouter:</strong> routes AI prompts to language model providers. Prompts may include lesson titles and goals but never your email or password.</li>
          <li><strong className="text-white">Sentry:</strong> captures error reports. No personally identifiable information is intentionally sent.</li>
        </ul>
      </Section>

      <Section title="4. Cookies & Sessions">
        <p>
          We use a single HTTP-only session cookie (<code className="text-purple-300">learnpath.sid</code>) to
          maintain your authenticated session. No third-party tracking cookies are set.
        </p>
      </Section>

      <Section title="5. Data Retention">
        <p>
          Account and learning data is retained while your account is active. On account deletion,
          data is removed within 30 days. Server logs are purged after 30 days.
        </p>
      </Section>

      <Section title="6. Security">
        <p>
          Password credentials and sessions are managed by Supabase Auth. Data in transit is encrypted via
          TLS. Database connections use SSL. We apply security headers (helmet) on every response.
        </p>
      </Section>

      <Section title="7. Your Rights">
        <p>You have the right to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Access the personal data we hold about you.</li>
          <li>Request correction of inaccurate data.</li>
          <li>Request deletion of your account and associated data.</li>
          <li>Object to or restrict processing in certain circumstances.</li>
        </ul>
        <p>
          To exercise these rights, email{' '}
          <a href="mailto:privacy@learnpath.ai" className="text-purple-400 hover:underline">
            privacy@learnpath.ai
          </a>
          .
        </p>
      </Section>

      <Section title="8. Children">
        <p>
          The Service is not directed at children under 13. We do not knowingly collect personal
          data from children under 13. If you believe a child has registered, contact us and we
          will remove the account promptly.
        </p>
      </Section>

      <Section title="9. Changes">
        <p>
          We may update this policy. Material changes will be communicated via email to registered
          users. Continued use after the effective date constitutes acceptance.
        </p>
      </Section>

      <Section title="10. Contact">
        <p>
          Privacy questions? Email{' '}
          <a href="mailto:privacy@learnpath.ai" className="text-purple-400 hover:underline">
            privacy@learnpath.ai
          </a>
          .
        </p>
      </Section>
    </LegalLayout>
  );
}
